name: push docker

on:
  push:
    branches: [main]

jobs:
  push_docker:

    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macOS-latest']
    
    steps:
      - name: checkout
        uses: actions/checkout@v4
        
      - name: setup_buildx
        uses: docker/setup-buildx-action@v3
      
      - name: login
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PAT}}

      - name: push_docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: davidanthonyvarley/hwapp:1.0.0