name: push docker

on:
  push:
    branches: [main]

jobs:
  push_docker:

    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macOS-latest']
    
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: log into docker image
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PAT}}
        
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3
      
      - name: build and push docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tag: davidanthonyvarley/hwapp:1.0.0