name: newbranch_action
author: dvarley
description: newbranch_action

inputs:
  brancher_name:
    description: 'the name of the person making the branch'
    required: false
    default: 'branching person'
  branch_name:
    description: 'the name of the new branch'
    required: true

outputs:
  message:
    description: 'the message shown to the new brancher'
    value: ${{steps.script-step.outputs.output-from-script}}

runs:
  using: 'composite'
  steps:
    - name: scriptshell
      id: script-shell
      shell: bash
      run: |
        echo "****************"
        echo "hello from my composite script. you have just created a new branch"
        echo "this is your input:"
        echo "\t${{inputs.brancher_name}}"
        echo "\t${{inputs.branch_name}}"
        echo ""
        name="${{inputs.brancher_name}}"
        branch="${{inputs.branch_name}}"
        message="${name}, you have created the ${branch}!"
        echo "\t message to be accessed by output in workflow${message}"
        
        echo "output-from-script=${message}" >> $GITHUB_OUTPUT
        echo "****************"

    - name: anothastep
      id: anothastep
      shell: bash
      run:
        echo "we can run multiple steps in this action"







