name: newbranch_action
author: dvarley
description: newbranch_action

inputs:
  brancher_name:
    description: 'the name of the person making the branch'
    required: false
    default: 'branching person'
  branch_name:
    description: 'the name of the new branch'
    required: true

outputs:
  message:
    description: 'the message shown to the new brancher'
    value: ${{steps.script-step.outputs.output-from-script}}

runs:
  using: 'composite'
  steps:
    - name: scriptshell
      id: script-step
      shell: bash
      run: |
        chmod +x .github/actions/newbranch_action/newbranch_script.sh
        bash .github/actions/newbranch_action/newbranch_script.sh


    - name: anothastep
      id: anothastep
      shell: bash
      run:
        echo "we can run multiple steps in this action"







