name: newbranch_action
author: dvarley
description: newbranch_action
inputs:
  brancher_name:
    description: 'the name of the person making the branch'
    required: false
    default: 'branching person'
  branch_name:
    description: 'the name of the new branch'
    required: true

outputs:
  message:
    description: 'the message shown to the new brancher'
    value: ${{steps.script-step.outputs.output-from-script}}

runs:
  using: 'composite'
  steps:
    - name: script shell
      id: script-shell
      shell: bash
      run: |
        echo "****************"
        echo "hello from my composite script. you have just created a new branch"
        echo "this is your input:"
        echo "\t${{inputs.bracher_name}}"
        echo "\t${{inputs.branch_name}}"
        echo ""
        name='${{inputs.brancher_name}}'
        branch='${{inputs.branch_name}}'
        message='$name, you have created the $name branch!'

        echo "output-frrom-script=$message" >> $GITHUB_OUTPUT
        echo "****************"

    - name: anotha step
      id: anotha step
      shell: bash
      run:
        echo "we can run multiple steps in this action"







